name: iOS TestFlight Release

on:
  push:
    tags:
      - 'v*' # v1.2.3, v2.0.0-b4 등 태그 푸시 시 트리거

jobs:
  release:
    runs-on: macos-14

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # 모든 태그·브랜치 히스토리 가져오기

      # --- 브랜치 검사 ---
      - name: Check if commit belongs to release/** branch
        id: check_branch
        run: |
          BRANCH=$(git branch -r --contains $GITHUB_SHA | grep 'origin/release/' || echo "")
          echo "branch=$BRANCH" >> $GITHUB_OUTPUT

      - name: Skip if not a release branch
        if: steps.check_branch.outputs.branch == ''
        run: |
          echo "This tag commit is not from a release branch. Exiting."
          exit 1

      # --- Xcode 워크어라운드 ---
      - name: Disable FileSystemSynchronizedGroups (Xcode workaround)
        run: defaults write com.apple.dt.Xcode IDEFileSystemSynchronizedGroupsEnabled -bool NO

      - name: Set Xcode version
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '15.2'

      # --- 의존성 설치 ---
      - name: Install Node modules
        run: npm install

      - name: Full clean of Pods and workspace
        run: |
          rm -rf ios/Pods ios/nailian.xcworkspace ios/Podfile.lock

      - name: Install CocoaPods dependencies
        working-directory: ios
        run: pod install
