name: iOS TestFlight Release

on:
  push:
    tags:
      - 'v*' # v1.2.3, v2.0.0-b4 등 태그 푸시 시 트리거

jobs:
  release:
    runs-on: macos-14

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # 모든 태그·브랜치 히스토리 가져오기

      # --- 브랜치 검사 ---
      - name: Check if commit belongs to release/** branch
        id: check_branch
        run: |
          BRANCH=$(git branch -r --contains $GITHUB_SHA | grep 'origin/release/' || echo "")
          echo "branch=$BRANCH" >> $GITHUB_OUTPUT

      - name: Skip if not a release branch
        if: steps.check_branch.outputs.branch == ''
        run: |
          echo "This tag commit is not from a release branch. Exiting."
          exit 1

      # --- Xcode 워크어라운드 ---
      - name: Disable FileSystemSynchronizedGroups (Xcode workaround)
        run: defaults write com.apple.dt.Xcode IDEFileSystemSynchronizedGroupsEnabled -bool NO

      - name: Set Xcode version
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '15.2'

      # --- 의존성 설치 ---
      - name: Install Node modules
        run: npm install

      - name: Full clean of Pods and workspace
        run: |
          rm -rf ios/Pods ios/nailian.xcworkspace ios/Podfile.lock

      - name: Install CocoaPods dependencies
        working-directory: ios
        run: pod install

      # --- Xcode 프로젝트 패치 ---
      - name: Downgrade objectVersion in Xcode project
        run: |
          sed -i '' 's/objectVersion = 63;/objectVersion = 56;/g' ios/nailian.xcodeproj/project.pbxproj

      - name: Patch pbxproj to remove Xcode 16 specific features
        run: |
          # 1. PBXFileSystemSynchronizedRootGroup 섹션 제거
          awk '
          /^\/\* Begin PBXFileSystemSynchronizedRootGroup section \*\// {skip=1; next}
          /^\/\* End PBXFileSystemSynchronizedRootGroup section \*\// {skip=0; next}
          !skip {print}
          ' ios/nailian.xcodeproj/project.pbxproj > temp.pbxproj && mv temp.pbxproj ios/nailian.xcodeproj/project.pbxproj
          # 2. fileSystemSynchronizedGroups 속성 삭제
          sed -i '' '/fileSystemSynchronizedGroups = (/,/);/d' ios/nailian.xcodeproj/project.pbxproj

      - name: List available schemes
        run: xcodebuild -list -workspace ios/nailian.xcworkspace

      # --- Ruby 및 Fastlane 설정 ---
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2.2'

      - name: Install Fastlane & Bundler
        working-directory: ios
        run: |
          gem install fastlane -v 2.216.0
          gem install cocoapods -v 1.14.3
          gem install bundler
          bundle config set --local path 'vendor/bundle'
          bundle install --jobs=4 --retry=3

      # --- Fastlane 플러그인 설치 ---
      - name: Install Fastlane Versioning Plugin
        working-directory: ios
        run: |
          gem install fastlane-plugin-versioning
          echo 'gem "fastlane-plugin-versioning"' >> Gemfile
          bundle update

      - name: Create Pluginfile for Fastlane
        working-directory: ios
        run: |
          mkdir -p fastlane
          cat > fastlane/Pluginfile << 'EOL'
          # Autogenerated by fastlane
          gem "fastlane-plugin-versioning"
          EOL

      # --- 코드 서명 설정 ---
      - name: Setup keychain for code signing
        working-directory: ios
        run: |
          security create-keychain -p "${{ secrets.KEYCHAIN_PASSWORD }}" build.keychain
          security default-keychain -s build.keychain
          security unlock-keychain -p "${{ secrets.KEYCHAIN_PASSWORD }}" build.keychain
          security set-keychain-settings -t 3600 -u build.keychain

      - name: Configure fastlane match
        run: |
          cat > ios/fastlane/.match << 'EOL'
          git_url("${{ secrets.MATCH_GIT_URL }}")
          git_branch("master")
          storage_mode("git")
          type("appstore")
          app_identifier("nailian.app")
          username("${{ secrets.APPLE_ID }}")
          team_id("${{ secrets.TEAM_ID }}")
          EOL

      # --- Fastlane 실행 ---
      - name: Run Fastlane auto_release
        working-directory: ios
        env:
          CI: true
          BUNDLE_GEMFILE: ${{ github.workspace }}/ios/Gemfile
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          MATCH_GIT_URL: ${{ secrets.MATCH_GIT_URL }}
          FASTLANE_USER: ${{ secrets.FASTLANE_USER }}
          KEYCHAIN_NAME: build.keychain
          KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
          APP_STORE_CONNECT_API_KEY_KEY_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_ID }}
          APP_STORE_CONNECT_API_KEY_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_API_ISSUER_ID }}
          APP_STORE_CONNECT_API_KEY_KEY: ${{ secrets.APP_STORE_CONNECT_API_KEY_CONTENT }}
          APPLE_ID: ${{ secrets.APPLE_ID }}
          FASTLANE_ITC_TEAM_ID: ${{ secrets.FASTLANE_ITC_TEAM_ID }}
          FASTLANE_TEAM_ID: ${{ secrets.FASTLANE_TEAM_ID }}
          APP_IDENTIFIER: 'nailian.app'
        run: bundle exec fastlane auto_release
